import{a as w,S as F,i as m}from"./assets/vendor-Db2TdIkw.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const p=async(e,o=1,s=15)=>{const a="49447810-de68c09371bf9037b3e54ca3c",t="https://pixabay.com/api/";try{return(await w.get(t,{params:{key:a,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:s}})).data}catch(r){return console.error(r),{hits:[],totalHits:0}}},q=new F(".gallery a");function A(e){e.innerHTML=""}function L(e,o){const s=e.map(({webformatURL:a,largeImageURL:t,tags:r,likes:l,views:v,comments:B,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${t}">
          <img class="gallery-image" src="${a}" alt="${r}" />
        </a>
        <ul class="cards-data">
          <li class="card-data"><h3>Likes</h3><p>${l}</p></li>
          <li class="card-data"><h3>Views</h3><p>${v}</p></li>
          <li class="card-data"><h3>Comments</h3><p>${B}</p></li>
          <li class="card-data"><h3>Downloads</h3><p>${S}</p></li>
        </ul>
      </li>
    `).join("");o.insertAdjacentHTML("beforeend",s),q.refresh()}function u(){m.error({backgroundColor:"#EF4040",messageColor:"#FAFAFB",theme:"dark",progressBarColor:"#B51B1B",maxWidth:"432",messageSize:"16",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}function i(e){const o=document.querySelector(".loader");e?o.classList.remove("visually-hidden"):o.classList.add("visually-hidden")}const f=document.querySelector(".form"),n=document.querySelector(".gallery"),c=document.querySelector(".btn-load-more"),y=document.querySelector(".loader");let d=1,h="",b=0;f.addEventListener("submit",async e=>{e.preventDefault(),A(n),c.classList.add("visually-hidden");const o=e.target["search-text"].value.trim();if(!o){m.error({backgroundColor:"#EF4040",messageColor:"#FAFAFB",theme:"dark",progressBarColor:"#B51B1B",maxWidth:"432",messageSize:"16",position:"topRight",message:"Input field should not be empty."});return}h=o,d=1,i(!0);try{const{hits:s,totalHits:a}=await p(h,d);b=a,s.length===0?u():(L(s,n),g(s.length>0))}catch{u()}finally{i(!1),f.reset()}});c.addEventListener("click",async()=>{d+=1,i(!0),y.classList.remove("visually-hidden");try{const{hits:e}=await p(h,d);e.length===0||n.children.length>=b?(m.error({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#EF4040"}),g(!1)):(L(e,n),g(!0),C())}catch{u()}finally{i(!1),y.classList.add("visually-hidden")}});function g(e){e?c.classList.remove("visually-hidden"):c.classList.add("visually-hidden")}function C(){const e=document.querySelectorAll(".gallery-item");if(e.length>0){const o=e[e.length-1],{height:s}=o.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
