import{a as F,S as C,i as c}from"./assets/vendor-Db2TdIkw.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(r){if(r.ep)return;r.ep=!0;const t=o(r);fetch(r.href,t)}})();const b=async(e,s=1,o=15)=>{const a="49447810-de68c09371bf9037b3e54ca3c",r="https://pixabay.com/api/";try{return(await F.get(r,{params:{key:a,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:o}})).data}catch(t){return console.error(t),{hits:[],totalHits:0}}},E=new C(".gallery a");function w(e){e.innerHTML=""}function L(e,s){const o=e.map(({webformatURL:a,largeImageURL:r,tags:t,likes:i,views:v,comments:B,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r}">
          <img class="gallery-image" src="${a}" alt="${t}" />
        </a>
        <ul class="cards-data">
          <li class="card-data"><h3>Likes</h3><p>${i}</p></li>
          <li class="card-data"><h3>Views</h3><p>${v}</p></li>
          <li class="card-data"><h3>Comments</h3><p>${B}</p></li>
          <li class="card-data"><h3>Downloads</h3><p>${S}</p></li>
        </ul>
      </li>
    `).join("");s.insertAdjacentHTML("beforeend",o),E.refresh()}function g(){c.error({backgroundColor:"#EF4040",messageColor:"#FAFAFB",theme:"dark",progressBarColor:"#B51B1B",maxWidth:"432",messageSize:"16",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}function d(e){const s=document.querySelector(".loader");e?s.classList.remove("visually-hidden"):s.classList.add("visually-hidden")}const y=document.querySelector(".form"),l=document.querySelector(".gallery"),u=document.querySelector(".btn-load-more"),p=document.querySelector(".loader");let h=1,m="",f=0;u.addEventListener("click",async()=>{h+=1,d(!0),p.classList.remove("visually-hidden");try{const{hits:e}=await b(m,h);e.length===0||l.children.length>=f?(c.error({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#EF4040"}),n(!1)):(L(e,l),l.children.length>=f?(n(!1),c.error({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#EF4040"})):n(!0),q())}catch{g()}finally{d(!1),p.classList.add("visually-hidden")}});y.addEventListener("submit",async e=>{e.preventDefault(),w(l),u.classList.add("visually-hidden");const s=e.target["search-text"].value.trim();if(!s){c.error({backgroundColor:"#EF4040",messageColor:"#FAFAFB",theme:"dark",progressBarColor:"#B51B1B",maxWidth:"432",messageSize:"16",position:"topRight",message:"Input field cannot be empty."});return}m=s,h=1,d(!0);try{const{hits:o,totalHits:a}=await b(m,h);f=a,o.length===0?g():(L(o,l),l.children.length>=f?(n(!1),c.error({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#EF4040"})):n(!0))}catch{g()}finally{d(!1),y.reset()}});function n(e){e?u.classList.remove("visually-hidden"):u.classList.add("visually-hidden")}function q(){const e=document.querySelectorAll(".gallery-item");if(e.length>0){const s=e[e.length-1],{height:o}=s.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
